---
- name: apt openresty key
  apt_key:
    id: 97DB7443D5EDEB74
    url: https://www.openresty.org/package/pubkey.gpg
- name: apt openresty repo
  copy:
    src:  apt-openresty
    dest: /etc/apt/sources.list.d/openresty.list
- name: install packages
  apt:
    name: "{{item}}"
    update_cache: yes
    install_recommends: yes
  with_items:
    - bind9
    - dehydrated
    - openresty
    - openresty-restydoc
- name: install dehydrated config
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0755
  with_items:
    - src: dehydrated-nsupdate.sh
      dest: /etc/dehydrated/nsupdate.sh
    - src: dehydrated-dns.sh
      dest: /etc/dehydrated/conf.d/dns.sh
    - src: dehydrated-cron.sh
      dest: /etc/cron.hourly/dehydrated
    - src: dehydrated-nsupdate.key
      dest: /etc/dehydrated/nsupdate.key
- name: dehydrated hostname
  copy:
    content: "{{inventory_hostname}}\n"
    dest: /etc/dehydrated/domains.txt
- name: initialize dehydrated
  command: dehydrated -c
  args:
    creates: /var/lib/dehydrated/certs/{{inventory_hostname}}/cert.pem
- name: certificate links
  file:
    state: link
    src: /var/lib/dehydrated/certs/{{inventory_hostname}}/{{item.src}}
    dest: /usr/local/openresty/nginx/conf/{{item.dest}}
  with_items:
    - src: fullchain.pem
      dest: cert.pem
    - src: privkey.pem
      dest: cert.key
- name: nginx config
  template:
    src: nginx.conf
    dest: /usr/local/openresty/nginx/conf/nginx.conf
  notify:
    restart nginx
- name: install lua modules
  copy:
    src: "{{item}}.lua"
    dest: /usr/local/openresty/lualib/{{item}}.lua
  with_items:
    - doh
    - base64url
